---
- hosts: web
  tasks:
    - name: create a muitple directories
      file:
        path: "{{ item.dest }}"
        state: directory
      with_items:
        - {dest: '/opt/dev1'}
        - {dest: '/home/dev2'}
        - {dest: '/root/dev3'} 
